  name: quizify
  description: "A new Flutter project."
  publish_to: 'none'
  version: 0.1.0

  environment:
    sdk: ">=3.5.0 <4.0.0"

  dependencies:
    flutter:
      sdk: flutter
    provider: ^6.1.2
    reward_popup: ^0.0.7
    shared_preferences: ^2.3.3

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0
    flutter_launcher_icons: ^0.14.2

  flutter_icons:
    android: true
    ios: false
    image_path_android: "assets/icon/icon.png"


  flutter:
    uses-material-design: true
    assets:
      - assets/images/
      - assets/icon/icon.png
