  name: quiz_app
  description: "A new Flutter project."
  publish_to: 'none'
  version: 0.1.0

  environment:
    sdk: ">=3.5.0 <4.0.0"

  dependencies:
    build_runner: ^2.4.15
    cached_network_image: ^3.4.1
    circular_countdown_timer: ^0.2.4
    cloud_firestore: ^5.6.6
    connectivity_plus: ^6.1.3
    email_validator: ^3.0.0
    firebase_auth: ^5.5.2
    firebase_core: ^3.13.0
    flutter:
      sdk: flutter
    flutter_launcher_icons: ^0.14.3
    flutter_staggered_grid_view: ^0.7.0
    google_sign_in: ^6.3.0
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    hive_generator: ^2.0.1
    http: ^1.3.0
    image_picker: ^1.1.2
    intl: ^0.20.2
    lottie: ^3.3.1
    path_provider: ^2.1.5
    percent_indicator: ^4.2.5
    permission_handler: ^12.0.0+1
    provider: ^6.1.2
    shared_preferences: ^2.3.3
    skeletonizer: ^1.4.3
    social_sharing_plus: ^1.2.3

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^4.0.0

  flutter_icons:
    android: "launcher_icon"
    ios: false
    image_path: "assets/images/final_logo.png"


  flutter:
    uses-material-design: true
    assets:
      - assets/images/
      - assets/animation/
