// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPsETNmF5kRT2rGUv2FwmYJaSQgEzNL-I',
    appId: '1:1063720040132:web:153375aca126083c7d7b91',
    messagingSenderId: '1063720040132',
    projectId: 'quiz-app-f1b31',
    authDomain: 'quiz-app-f1b31.firebaseapp.com',
    storageBucket: 'quiz-app-f1b31.firebasestorage.app',
    measurementId: 'G-4NVQYC08S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeSFAkcXHjpxfjdkD1GL_QZjH5JuXXJOQ',
    appId: '1:1063720040132:android:b0c8aac1d1a2a2077d7b91',
    messagingSenderId: '1063720040132',
    projectId: 'quiz-app-f1b31',
    storageBucket: 'quiz-app-f1b31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Y7NfgT2Fv48qyNaY0TjQcFGB6vePxws',
    appId: '1:1063720040132:ios:c73224e40fafbc4d7d7b91',
    messagingSenderId: '1063720040132',
    projectId: 'quiz-app-f1b31',
    storageBucket: 'quiz-app-f1b31.firebasestorage.app',
    iosClientId: '1063720040132-p58t44o7lhl8ekts03q5p2hk0t0lhpt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Y7NfgT2Fv48qyNaY0TjQcFGB6vePxws',
    appId: '1:1063720040132:ios:c73224e40fafbc4d7d7b91',
    messagingSenderId: '1063720040132',
    projectId: 'quiz-app-f1b31',
    storageBucket: 'quiz-app-f1b31.firebasestorage.app',
    iosClientId: '1063720040132-p58t44o7lhl8ekts03q5p2hk0t0lhpt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPsETNmF5kRT2rGUv2FwmYJaSQgEzNL-I',
    appId: '1:1063720040132:web:c0902e1a5c1098d27d7b91',
    messagingSenderId: '1063720040132',
    projectId: 'quiz-app-f1b31',
    authDomain: 'quiz-app-f1b31.firebaseapp.com',
    storageBucket: 'quiz-app-f1b31.firebasestorage.app',
    measurementId: 'G-QQ636MM199',
  );
}
